-- Run this in Supabase SQL Editor.
create table if not exists public.tax_returns (
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 tax_year text not null,
 status text not null default 'DRAFT' check (status in ('DRAFT','SUBMITTED','UNDER_REVIEW','ACCEPTED','REJECTED')),
 employment_income numeric(18,2) default 0,
 business_income numeric(18,2) default 0,
 rental_income numeric(18,2) default 0,
 financial_income numeric(18,2) default 0,
 capital_gain numeric(18,2) default 0,
 other_income numeric(18,2) default 0,
 investment numeric(18,2) default 0,
 expenditure numeric(18,2) default 0,
 assets numeric(18,2) default 0,
 liabilities numeric(18,2) default 0,
 withholding numeric(18,2) default 0,
 advance_tax numeric(18,2) default 0,
 gross_income numeric(18,2) default 0,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);
alter table public.tax_returns enable row level security;
drop policy if exists "users can read own returns" on public.tax_returns;
create policy "users can read own returns" on public.tax_returns for select to authenticated using (auth.uid()=user_id);
drop policy if exists "users can insert own returns" on public.tax_returns;
create policy "users can insert own returns" on public.tax_returns for insert to authenticated with check (auth.uid()=user_id);
drop policy if exists "users can update own returns" on public.tax_returns;
create policy "users can update own returns" on public.tax_returns for update to authenticated using (auth.uid()=user_id) with check (auth.uid()=user_id);
